apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fortune-pod
  name: fortune-pod
spec:
  containers:
  - args:
    - sleep
    - "100000"
    image: centos:7
    name: fortune-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
