apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fortune-pod
  name: fortune-pod
spec:
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
  containers:
  - image: ubuntu
    name: fortune-pod
    volumeMounts:
    - mountPath: /html
      name: cache-volume
  
  - args:
    - apt-get update;
      apt-get install fortune-mod -y;
      while true; do /usr/games/fortune > /html/index.html; sleep 5; done

  - image: nginx
    name: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
      
      




    
 
